services:
  - type: web
    name: niremind-frontend
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    envVars:
      - key: NODE_VERSION
        value: 20.15.1
    autoDeploy: true
    port: 3000