services:
  - type: web
    name: Event Mastarz
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn -w 4 -b 0.0.0.0:10000 app:app
      gunicorn -k eventlet -w 1 app:app