"""added a category column in the events model

Revision ID: b4aeb57566fa
Revises: f73c46de8be9
Create Date: 2024-10-22 09:27:39.969559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4aeb57566fa'
down_revision = 'f73c46de8be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_new',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('time', sa.Time(), nullable=False),
        sa.Column('location', sa.String(length=100), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=False, server_default='All'),  # Create the new table with the category column
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.execute("INSERT INTO events_new (id, title, description, date, time, location, created_by, created_at) SELECT id, title, description, date, time, location, created_by, created_at FROM events")  # Copy the data from the old table to the new table
    op.drop_table('events')  # Drop the old table
    op.rename_table('events_new', 'events')  # Rename the new table to the old table name


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_event', ['user_id', 'event_id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
